In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score



In [8]:
# Get Mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# build masks 
masktrain = (y_train == 0) | (y_train == 8)
masktest = (y_test == 0) | (y_test == 8)
# Apply masks
X_train = X_train[masktrain]
y_train = y_train[masktrain]
X_test1 = X_test[masktest]
y_test1 = y_test[masktest]

In [9]:
#Resahpe the dataset
X_train = X_train.reshape(X_train.shape[0] , X_train.shape[1]* X_train.shape[2])  
X_test1 = X_test1.reshape(X_test1.shape[0] , X_test1.shape[1]* X_test1.shape[2])  
X_test = X_test.reshape(X_test.shape[0] , X_test.shape[1]* X_test.shape[2])  

In [10]:
#build the logistic regression
regressor = LogisticRegression(random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred1 = regressor.predict(X_test1)


c:\Users\Juliana\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
#Evaluate whit all numbers
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ', accuracy_score(y_test, y_pred))

[[ 973    0    0    0    0    0    0    0    7    0]
 [   3    0    0    0    0    0    0    0 1132    0]
 [ 474    0    0    0    0    0    0    0  558    0]
 [ 173    0    0    0    0    0    0    0  837    0]
 [ 118    0    0    0    0    0    0    0  864    0]
 [ 157    0    0    0    0    0    0    0  735    0]
 [ 558    0    0    0    0    0    0    0  400    0]
 [ 262    0    0    0    0    0    0    0  766    0]
 [  15    0    0    0    0    0    0    0  959    0]
 [  57    0    0    0    0    0    0    0  952    0]]
Accuracy:  0.1932


In [12]:
#Evaluate whit not numbers to 8
cm2 = confusion_matrix(y_test1, y_pred1)
print(cm2)
print('Accuracy: ', accuracy_score(y_test1, y_pred1))

[[973   7]
 [ 15 959]]
Accuracy:  0.9887410440122825


the accuracy when we try de data known for the model is very high, it allows to belive in its predictions, but whr we try all the numbers de score is not aporpiate for this situation, is not a low score, but it does not understain a number so it makes nonconfiable model