In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score



In [68]:
# Get Mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# build masks 
masktrain = (y_train >= 0) & (y_train <= 8)
masktest = (y_test >= 0) & (y_test <= 8)
# Apply masks
X_train = X_train[masktrain]
y_train = y_train[masktrain]
X_test1 = X_test[masktest]
y_test1 = y_test[masktest]

In [69]:
#Resahpe the dataset
X_train = X_train.reshape(X_train.shape[0] , X_train.shape[1]* X_train.shape[2])  
X_test1 = X_test1.reshape(X_test1.shape[0] , X_test1.shape[1]* X_test1.shape[2])  
X_test = X_test.reshape(X_test.shape[0] , X_test.shape[1]* X_test.shape[2])  

In [70]:
#build the logistic regression
regressor = LogisticRegression(random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred1 = regressor.predict(X_test1)


c:\Users\Juliana\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [71]:
#Evaluate whit all numbers
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ', accuracy_score(y_test, y_pred))

[[ 963    0    1    3    0    4    6    2    1    0]
 [   0 1116    3    2    1    1    4    1    7    0]
 [   4   12  916   20   13    3   12   10   42    0]
 [   4    1   18  921    2   25    3   14   22    0]
 [   1    1    4    5  942    0   10    6   13    0]
 [  11    2    2   33    9  786   13    4   32    0]
 [   8    2    8    2    6   15  913    2    2    0]
 [   2    9   20    5   10    1    0  977    4    0]
 [   7   11    7   20    8   26   10   10  875    0]
 [  12   12    2   24  504   18    0  390   47    0]]
Accuracy:  0.8409


In [72]:
#Evaluate whit not numbers to 8
cm2 = confusion_matrix(y_test1, y_pred1)
print(cm2)
print('Accuracy: ', accuracy_score(y_test1, y_pred1))

[[ 963    0    1    3    0    4    6    2    1]
 [   0 1116    3    2    1    1    4    1    7]
 [   4   12  916   20   13    3   12   10   42]
 [   4    1   18  921    2   25    3   14   22]
 [   1    1    4    5  942    0   10    6   13]
 [  11    2    2   33    9  786   13    4   32]
 [   8    2    8    2    6   15  913    2    2]
 [   2    9   20    5   10    1    0  977    4]
 [   7   11    7   20    8   26   10   10  875]]
Accuracy:  0.9352686019352686


the accuracy when we try de data known for the model is very high, it allows to belive in its predictions, but whr we try all the numbers de score is not aporpiate for this situation, is not a low score, but it does not understain a number so it makes nonconfiable model